/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pozo;

import dominio.Ficha;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author tacot
 */
public class pruebaDeFuncionabilidad extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pruebaDeFuncionabilidad.class.getName());

    private Pozo instance;
            
    /**
     * Creates new form NewJFrame
     */
    public pruebaDeFuncionabilidad() {
        initComponents();
        instance = Pozo.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sacarFicha = new javax.swing.JButton();
        reiniciarPozo = new javax.swing.JButton();
        agregarFichas = new javax.swing.JButton();
        repartirfichas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sacarFicha.setText("sacarFicha");
        sacarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacarFichaActionPerformed(evt);
            }
        });

        reiniciarPozo.setText("reiniciarPozo");
        reiniciarPozo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarPozoActionPerformed(evt);
            }
        });

        agregarFichas.setText("agregarFichas");
        agregarFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarFichasActionPerformed(evt);
            }
        });

        repartirfichas.setText("repartirfichas");
        repartirfichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repartirfichasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarFichas)
                            .addComponent(reiniciarPozo)
                            .addComponent(sacarFicha)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(repartirfichas)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(sacarFicha)
                .addGap(62, 62, 62)
                .addComponent(reiniciarPozo)
                .addGap(73, 73, 73)
                .addComponent(agregarFichas)
                .addGap(53, 53, 53)
                .addComponent(repartirfichas)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sacarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacarFichaActionPerformed
        instance.getFichaAlAzar();
    }//GEN-LAST:event_sacarFichaActionPerformed

    private void reiniciarPozoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarPozoActionPerformed
        instance.reiniciarPozo();
    }//GEN-LAST:event_reiniciarPozoActionPerformed

    private void agregarFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarFichasActionPerformed
        List<Ficha> fichas = new ArrayList();
        fichas.add(new Ficha(1,2));
        fichas.add(new Ficha(4,3));
        instance.setFichas(fichas);
    }//GEN-LAST:event_agregarFichasActionPerformed

    private void repartirfichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repartirfichasActionPerformed
        instance.getFichasRepartidas(3, 4);
    }//GEN-LAST:event_repartirfichasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pruebaDeFuncionabilidad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarFichas;
    private javax.swing.JButton reiniciarPozo;
    private javax.swing.JButton repartirfichas;
    private javax.swing.JButton sacarFicha;
    // End of variables declaration//GEN-END:variables
}
