package inicio;

import ItemsConFondo.PanelConFondo;
import com.formdev.flatlaf.FlatLightLaf;
import contenedorMVC.Icomponente;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import observers.IObserver;

/**
 *
 * @author tacot
 */
public class VistaInicio extends javax.swing.JFrame implements Icomponente{

    private final ModeloInicio modelo;
    private final String urlFondo;
    private final String urlFuente;
    private IObserver observerJugar;
    private IObserver observerSalir;
    private IObserver observerVolver;
    private IObserver observerCrearSala;
    private IObserver observerUnirseASala;

    /**
     * Creates new form VistaInicio
     *
     * @param modelo
     */
    public VistaInicio(ModeloInicio modelo) {
        this.setUndecorated(true);
        this.modelo = modelo;
        modelo.setObservadorDeBoton(new AccionCambiarTextoBotones());
        this.urlFondo = modelo.getRutaFondo();
        this.urlFuente = modelo.getRutaFuente();
        initComponents();
        cargarEstilos(urlFuente);
        btnVolver.setVisible(false);
        btnVolver.setPreferredSize(new Dimension(50, 50));

    }

    /**
     * Metodo que permite cargar estilos personalizados en el programa
     *
     * @param fuente
     */
    public void cargarEstilos(String fuente) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());

            Titulo.setFont(VistaInicio.cargarFuente(fuente, 44f));
            btnUnirseSalaySalir.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnCrearSalayJugar.setFont(VistaInicio.cargarFuente(fuente, 30f));

        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(VistaInicio.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    public static Font cargarFuente(String ruta, float tamaño) {
        try {
            InputStream is = VistaInicio.class.getResourceAsStream(ruta);
            Font fuente = Font.createFont(Font.TRUETYPE_FONT, is);
            return fuente.deriveFont(tamaño);
        } catch (FontFormatException | IOException e) {
            return new Font("SansSerif", Font.PLAIN, (int) tamaño);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new PanelConFondo(urlFondo);
        Titulo = new javax.swing.JLabel();
        btnUnirseSalaySalir = new javax.swing.JButton();
        btnCrearSalayJugar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Domino Online");
        Titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnUnirseSalaySalir.setForeground(new java.awt.Color(255, 255, 255));
        btnUnirseSalaySalir.setText("Salir");
        btnUnirseSalaySalir.setToolTipText("");
        btnUnirseSalaySalir.setBorderPainted(false);
        btnUnirseSalaySalir.setContentAreaFilled(false);
        btnUnirseSalaySalir.setFocusable(false);
        btnUnirseSalaySalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseSalaySalirActionPerformed(evt);
            }
        });

        btnCrearSalayJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearSalayJugar.setText("Jugar");
        btnCrearSalayJugar.setBorderPainted(false);
        btnCrearSalayJugar.setContentAreaFilled(false);
        btnCrearSalayJugar.setFocusable(false);
        btnCrearSalayJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSalayJugarActionPerformed(evt);
            }
        });

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo/back.png"))); // NOI18N
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setFocusPainted(false);
        btnVolver.setFocusable(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCrearSalayJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUnirseSalaySalir, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(377, 377, 377))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnVolver)
                .addGap(110, 110, 110)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(btnCrearSalayJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(btnUnirseSalaySalir, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearSalayJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSalayJugarActionPerformed
        if (modelo.getEstadoBotones()) {
            ejecutarAccionJugar();
            this.btnVolver.setVisible(true);
        } else {
            ejecutarAccionCrearSala();
        }
    }//GEN-LAST:event_btnCrearSalayJugarActionPerformed

    private void btnUnirseSalaySalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseSalaySalirActionPerformed
        if (modelo.getEstadoBotones()) {
            ejecutarAccionSalir();
        } else {
            ejecutarAccionUnirseASala();
        }
    }//GEN-LAST:event_btnUnirseSalaySalirActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed

        ejecutarAccionVolver();
        this.btnVolver.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    public void setObserverJugar(IObserver observerJugar) {
        this.observerJugar = observerJugar;
    }

    public void setObserverSalir(IObserver observerSalir) {
        this.observerSalir = observerSalir;
    }

    public void setObserverVolver(IObserver observerVolver) {
        this.observerVolver = observerVolver;
    }

    public void setObserverCrearSala(IObserver observerCrearSala) {
        this.observerCrearSala = observerCrearSala;
    }

    public void setObserverUnirseASala(IObserver observerUnirseASala) {
        this.observerUnirseASala = observerUnirseASala;
    }

    public void ejecutarAccionJugar() {
        if (observerJugar != null) {
            observerJugar.actualizar();
        }
    }

    public void ejecutarAccionSalir() {
        if (observerSalir != null) {
            observerSalir.actualizar();
        }
    }

    public void ejecutarAccionVolver() {
        if (observerVolver != null) {
            observerVolver.actualizar();
        }
    }

    public void ejecutarAccionCrearSala() {
        if (observerCrearSala != null) {
            observerCrearSala.actualizar();
        }
    }

    public void ejecutarAccionUnirseASala() {
        if (observerUnirseASala != null) {
            observerUnirseASala.actualizar();
        }
    }

    public void cambiarTextoBotones(String txtBtn1, String txtBtn2) {

        this.btnCrearSalayJugar.setText(txtBtn1);
        this.btnUnirseSalaySalir.setText(txtBtn2);
    }

    private class AccionCambiarTextoBotones implements IObserver {

        public AccionCambiarTextoBotones() {
        }

        @Override
        public void actualizar() {
            cambiarTextoBotones(modelo.getTextoBtn1(), modelo.getTextoBtn2());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCrearSalayJugar;
    private javax.swing.JButton btnUnirseSalaySalir;
    private javax.swing.JButton btnVolver;
    // End of variables declaration//GEN-END:variables
}
