package crearSala;

import com.formdev.flatlaf.FlatLightLaf;
import inicio.VistaInicio;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utileria.BotonRedondeado;
import utileria.PanelConFondo;
import utileria.TextFieldRedondeado;

/**
 *
 * @author tacot
 */
public class VistaCrearSala extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCrearSala.class.getName());

    private final ModeloCrearSala modelo;
    private final String urlFondo;
    private final String urlFuente;
    
    /**
     * Creates new form VistaCrearSala
     */
    public VistaCrearSala() {
        
        this.setUndecorated(true);
        modelo = new ModeloCrearSala();
        urlFondo = modelo.getRutaFondo();
        urlFuente = modelo.getRutaFuente();
        initComponents();
        cargarEstilos(urlFuente);
    }
    
    /**
     * Metodo que permite cargar estilos personalizados en el programa
     *
     * @param fuente
     */
    public void cargarEstilos(String fuente) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());

            txtTitulo.setFont(VistaInicio.cargarFuente(fuente, 44f));
            txtNombreJugador.setFont(VistaInicio.cargarFuente(fuente, 30f));
            TFnombre.setFont(VistaInicio.cargarFuente(fuente, 30f));
            txtFichas.setFont(VistaInicio.cargarFuente(fuente, 30f));
            txtAvatar.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnAtras.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnAdelante.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnCrear.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnCancelar.setFont(VistaInicio.cargarFuente(fuente, 30f));

        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(VistaInicio.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    public static Font cargarFuente(String ruta, float tamaño) {
        try {
            InputStream is = VistaInicio.class.getResourceAsStream(ruta);
            Font fuente = Font.createFont(Font.TRUETYPE_FONT, is);
            return fuente.deriveFont(tamaño);
        } catch (FontFormatException | IOException e) {
            return new Font("SansSerif", Font.PLAIN, (int) tamaño);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPricipal = new PanelConFondo(urlFondo);
        btnCrear = new BotonRedondeado();
        txtTitulo = new javax.swing.JLabel();
        btnCancelar = new BotonRedondeado();
        txtNombreJugador = new javax.swing.JLabel();
        TFnombre = new TextFieldRedondeado(10);
        txtFichas = new javax.swing.JLabel();
        txtAvatar = new javax.swing.JLabel();
        btnAdelante = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        avatar = new javax.swing.JLabel();
        rbtn4 = new javax.swing.JRadioButton();
        rbtn6 = new javax.swing.JRadioButton();
        rbtn5 = new javax.swing.JRadioButton();
        rbtn7 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPricipal.setPreferredSize(new java.awt.Dimension(1024, 624));

        btnCrear.setBackground(new java.awt.Color(192, 163, 115));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setBorderPainted(false);
        btnCrear.setContentAreaFilled(false);
        btnCrear.setDefaultCapable(false);
        btnCrear.setPreferredSize(new java.awt.Dimension(275, 61));

        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Crear sala");

        btnCancelar.setBackground(new java.awt.Color(192, 163, 115));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setDefaultCapable(false);
        btnCancelar.setPreferredSize(new java.awt.Dimension(275, 61));

        txtNombreJugador.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreJugador.setText("Nombre de jugador");
        txtNombreJugador.setPreferredSize(new java.awt.Dimension(44, 53));

        TFnombre.setBackground(new java.awt.Color(255, 255, 255));
        TFnombre.setForeground(new java.awt.Color(0, 0, 0));
        TFnombre.setPreferredSize(new java.awt.Dimension(44, 53));

        txtFichas.setForeground(new java.awt.Color(255, 255, 255));
        txtFichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFichas.setText("Fichas de inicio");
        txtFichas.setPreferredSize(new java.awt.Dimension(44, 53));

        txtAvatar.setForeground(new java.awt.Color(255, 255, 255));
        txtAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAvatar.setText("Avatar");
        txtAvatar.setPreferredSize(new java.awt.Dimension(44, 53));

        btnAdelante.setForeground(new java.awt.Color(255, 255, 255));
        btnAdelante.setText(">");
        btnAdelante.setBorderPainted(false);
        btnAdelante.setContentAreaFilled(false);

        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("<");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);

        avatar.setForeground(new java.awt.Color(255, 255, 255));
        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatares/avt1.png"))); // NOI18N
        avatar.setPreferredSize(new java.awt.Dimension(100, 100));
        avatar.setRequestFocusEnabled(false);

        rbtn4.setForeground(new java.awt.Color(255, 255, 255));
        rbtn4.setText("4");
        rbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn4ActionPerformed(evt);
            }
        });

        rbtn6.setForeground(new java.awt.Color(255, 255, 255));
        rbtn6.setText("6");
        rbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn6ActionPerformed(evt);
            }
        });

        rbtn5.setForeground(new java.awt.Color(255, 255, 255));
        rbtn5.setText("5");
        rbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn5ActionPerformed(evt);
            }
        });

        rbtn7.setForeground(new java.awt.Color(255, 255, 255));
        rbtn7.setText("7");
        rbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPricipalLayout = new javax.swing.GroupLayout(PanelPricipal);
        PanelPricipal.setLayout(PanelPricipalLayout);
        PanelPricipalLayout.setHorizontalGroup(
            PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPricipalLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelPricipalLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFichas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtn5)
                            .addComponent(rbtn4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn7)
                            .addComponent(rbtn6))
                        .addGap(60, 60, 60)))
                .addGap(0, 154, Short.MAX_VALUE)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(160, 160, 160))
        );
        PanelPricipalLayout.setVerticalGroup(
            PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPricipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn4)
                            .addComponent(rbtn6)))
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn5)
                    .addComponent(rbtn7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn4ActionPerformed
        if (rootPaneCheckingEnabled) {
            
        }
    }//GEN-LAST:event_rbtn4ActionPerformed

    private void rbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn7ActionPerformed

    private void rbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn5ActionPerformed

    private void rbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaCrearSala().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPricipal;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JLabel avatar;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JRadioButton rbtn4;
    private javax.swing.JRadioButton rbtn5;
    private javax.swing.JRadioButton rbtn6;
    private javax.swing.JRadioButton rbtn7;
    private javax.swing.JLabel txtAvatar;
    private javax.swing.JLabel txtFichas;
    private javax.swing.JLabel txtNombreJugador;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
