package crearSala;

import com.formdev.flatlaf.FlatLightLaf;
import inicio.VistaInicio;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import itemsRedondeados.BotonRedondeado;
import ItemsConFondo.PanelConFondo;
import contenedorMVC.Icomponente;
import itemsRedondeados.TextFieldRedondeado;
import javax.swing.ImageIcon;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import observers.IObserver;

/**
 *
 * @author tacot
 */
public class VistaCrearSala extends javax.swing.JFrame implements Icomponente {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaCrearSala.class.getName());

    private final ModeloCrearSala modelo;
    private final String urlFondo;
    private final String urlFuente;
    private IObserver observadorCrearSala;
    private IObserver observadorCancelar;
    private IObserver observadorSiguienteAvatar;
    private IObserver observadorAnteriorAvatar;

    /**
     * Creates new form VistaCrearSala
     *
     * @param modeloP
     */
    public VistaCrearSala(ModeloCrearSala modeloP) {

        this.setUndecorated(true);
        modelo = modeloP;
        urlFondo = modelo.getRutaFondo();
        urlFuente = modelo.getRutaFuente();
        modelo.setObservadorAvatar(new AccionAvatar());
        initComponents();
        cargarEstilos(urlFuente);
        avatar.setIcon(new ImageIcon(modelo.getImagen()));

        
    }

    /**
     * Metodo que permite cargar estilos personalizados en el programa
     *
     * @param fuente
     */
    public void cargarEstilos(String fuente) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());

            txtTitulo.setFont(VistaInicio.cargarFuente(fuente, 44f));
            txtNombreJugador.setFont(VistaInicio.cargarFuente(fuente, 30f));
            TFnombre.setFont(VistaInicio.cargarFuente(fuente, 30f));
            txtFichas.setFont(VistaInicio.cargarFuente(fuente, 30f));
            txtAvatar.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnAnteriorAvatar.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnSiguienteAvatar.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnCrear.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnCancelar.setFont(VistaInicio.cargarFuente(fuente, 30f));
            this.rbtn4.setFont(VistaInicio.cargarFuente(fuente, 30f));
            this.rbtn5.setFont(VistaInicio.cargarFuente(fuente, 30f));
            this.rbtn6.setFont(VistaInicio.cargarFuente(fuente, 30f));
            this.rbtn7.setFont(VistaInicio.cargarFuente(fuente, 30f));

        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(VistaInicio.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    public static Font cargarFuente(String ruta, float tamaño) {
        try {
            InputStream is = VistaInicio.class.getResourceAsStream(ruta);
            Font fuente = Font.createFont(Font.TRUETYPE_FONT, is);
            return fuente.deriveFont(tamaño);
        } catch (FontFormatException | IOException e) {
            return new Font("SansSerif", Font.PLAIN, (int) tamaño);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPricipal = new PanelConFondo(urlFondo);
        btnCrear = new BotonRedondeado();
        txtTitulo = new javax.swing.JLabel();
        btnCancelar = new BotonRedondeado();
        txtNombreJugador = new javax.swing.JLabel();
        TFnombre = new TextFieldRedondeado(10);
        txtFichas = new javax.swing.JLabel();
        txtAvatar = new javax.swing.JLabel();
        btnSiguienteAvatar = new javax.swing.JButton();
        btnAnteriorAvatar = new javax.swing.JButton();
        avatar = new javax.swing.JLabel();
        rbtn4 = new javax.swing.JRadioButton();
        rbtn6 = new javax.swing.JRadioButton();
        rbtn5 = new javax.swing.JRadioButton();
        rbtn7 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPricipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelPricipal.setPreferredSize(new java.awt.Dimension(1024, 624));

        btnCrear.setBackground(new java.awt.Color(192, 163, 115));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setBorderPainted(false);
        btnCrear.setContentAreaFilled(false);
        btnCrear.setDefaultCapable(false);
        btnCrear.setPreferredSize(new java.awt.Dimension(275, 61));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Crear sala");
        txtTitulo.setPreferredSize(new java.awt.Dimension(275, 61));

        btnCancelar.setBackground(new java.awt.Color(192, 163, 115));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setDefaultCapable(false);
        btnCancelar.setPreferredSize(new java.awt.Dimension(275, 61));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNombreJugador.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreJugador.setText("Gamertag");
        txtNombreJugador.setPreferredSize(new java.awt.Dimension(275, 61));

        TFnombre.setBackground(new java.awt.Color(255, 255, 255));
        TFnombre.setForeground(new java.awt.Color(0, 0, 0));
        TFnombre.setPreferredSize(new java.awt.Dimension(275, 61));

        txtFichas.setForeground(new java.awt.Color(255, 255, 255));
        txtFichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFichas.setText("Fichas de inicio");
        txtFichas.setPreferredSize(new java.awt.Dimension(275, 61));

        txtAvatar.setForeground(new java.awt.Color(255, 255, 255));
        txtAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAvatar.setText("Avatar");
        txtAvatar.setPreferredSize(new java.awt.Dimension(275, 61));

        btnSiguienteAvatar.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteAvatar.setText(">");
        btnSiguienteAvatar.setBorderPainted(false);
        btnSiguienteAvatar.setContentAreaFilled(false);
        btnSiguienteAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteAvatarActionPerformed(evt);
            }
        });

        btnAnteriorAvatar.setForeground(new java.awt.Color(255, 255, 255));
        btnAnteriorAvatar.setText("<");
        btnAnteriorAvatar.setBorderPainted(false);
        btnAnteriorAvatar.setContentAreaFilled(false);
        btnAnteriorAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorAvatarActionPerformed(evt);
            }
        });

        avatar.setForeground(new java.awt.Color(255, 255, 255));
        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatares/avt1.png"))); // NOI18N
        avatar.setPreferredSize(new java.awt.Dimension(100, 100));
        avatar.setRequestFocusEnabled(false);

        rbtn4.setForeground(new java.awt.Color(255, 255, 255));
        rbtn4.setText("4");
        rbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn4ActionPerformed(evt);
            }
        });

        rbtn6.setForeground(new java.awt.Color(255, 255, 255));
        rbtn6.setText("6");
        rbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn6ActionPerformed(evt);
            }
        });

        rbtn5.setForeground(new java.awt.Color(255, 255, 255));
        rbtn5.setText("5");
        rbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn5ActionPerformed(evt);
            }
        });

        rbtn7.setForeground(new java.awt.Color(255, 255, 255));
        rbtn7.setText("7");
        rbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPricipalLayout = new javax.swing.GroupLayout(PanelPricipal);
        PanelPricipal.setLayout(PanelPricipalLayout);
        PanelPricipalLayout.setHorizontalGroup(
            PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPricipalLayout.createSequentialGroup()
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(rbtn4)
                        .addGap(18, 18, 18)
                        .addComponent(rbtn5)
                        .addGap(18, 18, 18)
                        .addComponent(rbtn6)
                        .addGap(18, 18, 18)
                        .addComponent(rbtn7))
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFichas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(TFnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtNombreJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelPricipalLayout.createSequentialGroup()
                                .addComponent(btnAnteriorAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSiguienteAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPricipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PanelPricipalLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPricipalLayout.setVerticalGroup(
            PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPricipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn4)
                            .addComponent(rbtn5)
                            .addComponent(rbtn6)
                            .addComponent(rbtn7)))
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSiguienteAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAnteriorAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn4ActionPerformed

        this.rbtn5.setSelected(false);
        this.rbtn6.setSelected(false);
        this.rbtn7.setSelected(false);
    }//GEN-LAST:event_rbtn4ActionPerformed

    private void rbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn7ActionPerformed
        this.rbtn5.setSelected(false);
        this.rbtn6.setSelected(false);
        this.rbtn4.setSelected(false);
    }//GEN-LAST:event_rbtn7ActionPerformed

    private void rbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn5ActionPerformed
        this.rbtn4.setSelected(false);
        this.rbtn6.setSelected(false);
        this.rbtn7.setSelected(false);
    }//GEN-LAST:event_rbtn5ActionPerformed

    private void rbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn6ActionPerformed
        this.rbtn5.setSelected(false);
        this.rbtn4.setSelected(false);
        this.rbtn7.setSelected(false);
    }//GEN-LAST:event_rbtn6ActionPerformed
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ejecutarObservadorCancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        ejecutarObservadorCrearSala();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnAnteriorAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorAvatarActionPerformed
        ejecutarObservadorAnteriorAvatar();
    }//GEN-LAST:event_btnAnteriorAvatarActionPerformed

    private void btnSiguienteAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteAvatarActionPerformed
        ejecutarObservadorSiguienteAvatar();
    }//GEN-LAST:event_btnSiguienteAvatarActionPerformed

    public void setObservadorCrearSala(IObserver observadorCrearSala) {
        this.observadorCrearSala = observadorCrearSala;
    }

    public void setObservadorCanselar(IObserver observadorCancelar) {
        this.observadorCancelar = observadorCancelar;
    }

    public void ejecutarObservadorCrearSala() {
        this.observadorCrearSala.actualizar();
    }

    public void ejecutarObservadorCancelar() {
        this.observadorCancelar.actualizar();
    }

    public void setObservadorAdelanteAvatar(IObserver observadorAdelanteAvatar) {
        this.observadorSiguienteAvatar = observadorAdelanteAvatar;
    }

    public void setObservadorAtrasAvatar(IObserver observadorAtrasAvatar) {
        this.observadorAnteriorAvatar = observadorAtrasAvatar;
    }

    public void ejecutarObservadorSiguienteAvatar() {
        this.observadorSiguienteAvatar.actualizar();
    }

    public void ejecutarObservadorAnteriorAvatar() {
        this.observadorAnteriorAvatar.actualizar();
    }

    public void ejectutarAccionAvatar() {
        avatar.setIcon(new ImageIcon(modelo.getImagen()));
        repaint();
    }

    private class AccionAvatar implements IObserver {

        @Override
        public void actualizar() {
            ejectutarAccionAvatar();
        }
    }

    public JTextField getTFnombre() {
        return TFnombre;
    }

    public JRadioButton getRbtn4() {
        return rbtn4;
    }

    public JRadioButton getRbtn5() {
        return rbtn5;
    }

    public JRadioButton getRbtn6() {
        return rbtn6;
    }

    public JRadioButton getRbtn7() {
        return rbtn7;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPricipal;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JLabel avatar;
    private javax.swing.JButton btnAnteriorAvatar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnSiguienteAvatar;
    private javax.swing.JRadioButton rbtn4;
    private javax.swing.JRadioButton rbtn5;
    private javax.swing.JRadioButton rbtn6;
    private javax.swing.JRadioButton rbtn7;
    private javax.swing.JLabel txtAvatar;
    private javax.swing.JLabel txtFichas;
    private javax.swing.JLabel txtNombreJugador;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
