package mensajeAlerta;

import com.formdev.flatlaf.FlatLightLaf;
import inicio.VistaInicio;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import itemsRedondeados.BotonRedondeado;
import ItemsConFondo.PanelConFondo;
import javax.swing.JLabel;
import observers.IObserver;

/**
 *
 * @author tacot
 */
public class VistaMensaje extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMensaje.class.getName());
    private final ModeloMensaje modelo;
    private final String urlFondo;
    private final String urlFuente;
    private IObserver observadorAceptar;

    /**
     * Creates new form VistaMensaje
     * @param parent
     * @param modal
     * @param modelop
     */
    public VistaMensaje(java.awt.Frame parent, boolean modal, ModeloMensaje modelop) {
        super(parent, modal);
        this.setUndecorated(true);
        this.modelo = modelop;
        this.urlFondo = modelo.getRutaFondo();
        this.urlFuente = modelo.getRutaFuente();
        
        initComponents();
        cargarEstilos(urlFuente);
        this.txtTitulo.setText(modelo.getContenido());
        
    }
    
    public final void cargarEstilos(String fuente) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());

            btnAceptar.setFont(cargarFuente(fuente, 28f));
            txtTitulo.setFont(cargarFuente(fuente, 15f));

        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(VistaInicio.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    public static Font cargarFuente(String ruta, float tamaño) {
        try {
            InputStream is = VistaInicio.class.getResourceAsStream(ruta);
            Font fuente = Font.createFont(Font.TRUETYPE_FONT, is);
            return fuente.deriveFont(tamaño);
        } catch (FontFormatException | IOException e) {
            return new Font("SansSerif", Font.PLAIN, (int) tamaño);
        }
    }

    public void setObservadorAceptar(IObserver observadorAceptar) {
        this.observadorAceptar = observadorAceptar;
    }
    
    public void ejecutarObservadorAceptar(){
        observadorAceptar.actualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new PanelConFondo(urlFondo);
        txtTitulo = new javax.swing.JLabel();
        btnAceptar = new BotonRedondeado();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PanelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Haz perdido");

        btnAceptar.setBackground(new java.awt.Color(192, 163, 115));
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setDefaultCapable(false);
        btnAceptar.setRequestFocusEnabled(false);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ejecutarObservadorAceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    public JLabel getTxtTitulo() {
        return txtTitulo;
    }

    public void setTxtTitulo(JLabel txtTitulo) {
        this.txtTitulo = txtTitulo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
