package unirseASala;

import com.formdev.flatlaf.FlatLightLaf;
import inicio.VistaInicio;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import itemsRedondeados.BotonRedondeado;
import ItemsConFondo.PanelConFondo;
import contenedorMVC.Icomponente;
import itemsRedondeados.TextFieldRedondeado;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextField;
import observers.IObserver;

/**
 *
 * @author tacot
 */
public class VistaUnirseASala extends javax.swing.JFrame implements Icomponente {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaUnirseASala.class.getName());
    private final ModeloUnirseASala modelo;
    private final String urlFondo;
    private final String urlFuente;
    private IObserver observadorUnirseSala;
    private IObserver observadorCancelar;
    private IObserver observadorSiguienteAvatar;
    private IObserver observadorAnteriorAvatar;

    /**
     * Creates new form VistaUnirseASala
     * @param modeloUnirseASala
     */
    public VistaUnirseASala(ModeloUnirseASala modeloUnirseASala) {

        this.setUndecorated(true);
        modelo = modeloUnirseASala;
        urlFondo = modelo.getRutaFondo();
        urlFuente = modelo.getRutaFuente();
        initComponents();
        cargarEstilos(urlFuente);
        avatar.setIcon(new ImageIcon(modelo.getImagen()));
        modelo.setObservadorAvatar(new AccionAvatar());
    }

    /**
     * Metodo que permite cargar estilos personalizados en el programa
     *
     * @param fuente
     */
    public final void cargarEstilos(String fuente) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());

            txtTitulo.setFont(VistaInicio.cargarFuente(fuente, 44f));
            txtNombreJugador.setFont(VistaInicio.cargarFuente(fuente, 30f));
            TFnombre.setFont(VistaInicio.cargarFuente(fuente, 30f));
            txtFichas.setFont(VistaInicio.cargarFuente(fuente, 30f));
            TFcodigo.setFont(VistaInicio.cargarFuente(fuente, 30f));
            txtAvatar.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnAtras.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnAdelante.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnCrear.setFont(VistaInicio.cargarFuente(fuente, 30f));
            btnCancelar.setFont(VistaInicio.cargarFuente(fuente, 30f));

        } catch (UnsupportedLookAndFeelException ex) {
            System.getLogger(VistaInicio.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    public static Font cargarFuente(String ruta, float tamaño) {
        try {
            InputStream is = VistaInicio.class.getResourceAsStream(ruta);
            Font fuente = Font.createFont(Font.TRUETYPE_FONT, is);
            return fuente.deriveFont(tamaño);
        } catch (FontFormatException | IOException e) {
            return new Font("SansSerif", Font.PLAIN, (int) tamaño);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPricipal = new PanelConFondo(urlFondo);
        btnCrear = new BotonRedondeado();
        txtTitulo = new javax.swing.JLabel();
        btnCancelar = new BotonRedondeado();
        txtNombreJugador = new javax.swing.JLabel();
        TFnombre = new TextFieldRedondeado(10);
        TFcodigo = new TextFieldRedondeado(10);
        txtFichas = new javax.swing.JLabel();
        txtAvatar = new javax.swing.JLabel();
        btnAdelante = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        avatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPricipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelPricipal.setPreferredSize(new java.awt.Dimension(1024, 624));

        btnCrear.setBackground(new java.awt.Color(192, 163, 115));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Unirse");
        btnCrear.setToolTipText("");
        btnCrear.setBorderPainted(false);
        btnCrear.setContentAreaFilled(false);
        btnCrear.setDefaultCapable(false);
        btnCrear.setPreferredSize(new java.awt.Dimension(275, 61));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Unirse a sala");
        txtTitulo.setPreferredSize(new java.awt.Dimension(275, 61));

        btnCancelar.setBackground(new java.awt.Color(192, 163, 115));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setDefaultCapable(false);
        btnCancelar.setPreferredSize(new java.awt.Dimension(275, 61));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNombreJugador.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreJugador.setText("Gamertag");
        txtNombreJugador.setPreferredSize(new java.awt.Dimension(275, 61));

        TFnombre.setBackground(new java.awt.Color(255, 255, 255));
        TFnombre.setForeground(new java.awt.Color(0, 0, 0));
        TFnombre.setPreferredSize(new java.awt.Dimension(275, 61));

        TFcodigo.setBackground(new java.awt.Color(255, 255, 255));
        TFcodigo.setForeground(new java.awt.Color(0, 0, 0));
        TFcodigo.setToolTipText("Numero de fichas con las que va a iniciar el juego");
        TFcodigo.setPreferredSize(new java.awt.Dimension(275, 61));

        txtFichas.setForeground(new java.awt.Color(255, 255, 255));
        txtFichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFichas.setText("Codigo");
        txtFichas.setPreferredSize(new java.awt.Dimension(275, 61));

        txtAvatar.setForeground(new java.awt.Color(255, 255, 255));
        txtAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAvatar.setText("Avatar");
        txtAvatar.setPreferredSize(new java.awt.Dimension(275, 61));

        btnAdelante.setForeground(new java.awt.Color(255, 255, 255));
        btnAdelante.setText(">");
        btnAdelante.setBorderPainted(false);
        btnAdelante.setContentAreaFilled(false);
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });

        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("<");
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        avatar.setForeground(new java.awt.Color(255, 255, 255));
        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/avatares/avt1.png"))); // NOI18N
        avatar.setPreferredSize(new java.awt.Dimension(100, 100));
        avatar.setRequestFocusEnabled(false);

        javax.swing.GroupLayout PanelPricipalLayout = new javax.swing.GroupLayout(PanelPricipal);
        PanelPricipal.setLayout(PanelPricipalLayout);
        PanelPricipalLayout.setHorizontalGroup(
            PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPricipalLayout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelPricipalLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addComponent(TFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPricipalLayout.createSequentialGroup()
                                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(txtFichas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(TFnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(0, 159, Short.MAX_VALUE))
                            .addGroup(PanelPricipalLayout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelPricipalLayout.createSequentialGroup()
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAvatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(160, 160, 160))))
        );
        PanelPricipalLayout.setVerticalGroup(
            PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPricipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreJugador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtFichas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPricipalLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(PanelPricipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPricipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        ejecutarObservadorUnirseASala();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ejecutarObservadorCancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        ejecutarObservadorAnteriorAvatar();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        ejecutarObservadorSiguienteAvatar();
    }//GEN-LAST:event_btnAdelanteActionPerformed

    public void setObservadorCrearSala(IObserver observadorUnirseSala) {
        this.observadorUnirseSala = observadorUnirseSala;
    }

    public void setObservadorCanselar(IObserver observadorCancelar) {
        this.observadorCancelar = observadorCancelar;
    }

    public void ejecutarObservadorUnirseASala() {
        this.observadorUnirseSala.actualizar();
    }

    public void ejecutarObservadorCancelar() {
        this.observadorCancelar.actualizar();
    }

    public void setObservadorAdelanteAvatar(IObserver observadorAdelanteAvatar) {
        this.observadorSiguienteAvatar = observadorAdelanteAvatar;
    }

    public void setObservadorAtrasAvatar(IObserver observadorAtrasAvatar) {
        this.observadorAnteriorAvatar = observadorAtrasAvatar;
    }

    public void ejecutarObservadorSiguienteAvatar() {
        this.observadorSiguienteAvatar.actualizar();
    }

    public void ejecutarObservadorAnteriorAvatar() {
        this.observadorAnteriorAvatar.actualizar();
    }

    public void ejectutarAccionAvatar() {
        avatar.setIcon(new ImageIcon(modelo.getImagen()));
        repaint();
    }

    private class AccionAvatar implements IObserver {

        @Override
        public void actualizar() {
            ejectutarAccionAvatar();
        }
    }

    public JTextField getTFcodigo() {
        return TFcodigo;
    }

    public JTextField getTFnombre() {
        return TFnombre;
    }

    public JLabel getAvatar() {
        return avatar;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPricipal;
    private javax.swing.JTextField TFcodigo;
    private javax.swing.JTextField TFnombre;
    private javax.swing.JLabel avatar;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel txtAvatar;
    private javax.swing.JLabel txtFichas;
    private javax.swing.JLabel txtNombreJugador;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables
}
